### ISSUE TITLE
[CORE] Additional Packages

### ISSUE THREAD

**Issue by arcolinuxz** [arcolinux/sofirem-dev#17]
# [CORE Task]

### A list of additional packages to consider adding

- desktop trasher
- att
- rust desktop bin
- media-downloader
- mullvad-browser
- rustdeck
- docker
- docker-desktop

**Comment by arcolinuxz** [comment]
Apps already in:

    desktop trasher
    att


Apps that did not make it yet:

    rustdeck
    media-downloader
    mullvad-browser
    docker



Apps I do not find on AUR

    rust desktop bin - is it rustdesk-bin?
    docker-desktop

**Comment by DeltaCopy** [comment]
Closing this old task
