### ISSUE TITLE
[CORE] Additional Repositories

### ISSUE THREAD

**Issue by arcolinuxz** [arcolinux/sofirem-dev#18]
# [Core Task]

### Adding additional repositories

- ArcoLinux Spices
- Other repositories needed

**Comment by arcolinuxz** [comment]
I would not add more repositories
It will break their systems

Chaotic has changed their numbering system and makes it now very difficult to be integrated with any other distro

even dangerous

that is why I say 

get what you want and de-activate any repo you added again

**Comment by DeltaCopy** [comment]
not in scope of the app
