### ISSUE TITLE
[CORE] App Logging

### ISSUE THREAD

**Issue by DeltaCopy** [arcolinux/sofirem-dev#20]
# [CORE Task]

### To have traceability on what actions the app is doing, add logging functionality.

- Any actions regarding install/removal of packages should be logged into a file inside /var/log/sofirem

**Comment by DeltaCopy** [comment]
Any logging to the console, now use the logger framework.
This means those legacy `print("INFO"), print("DEBUG"), print("WARN"), print("ERROR")` - all have been removed.

The code now has:

`logger.info("msg")`
`logger.warn"msg")`
`logger.debug("msg")`
`logger.error("msg")`

**Comment by arcolinuxz** [comment]
I think this one is finished?

**Comment by DeltaCopy** [comment]
Closing, logger module is now is use
