### ISSUE TITLE
[BUG] paru-git and paru-bin in conflict

### ISSUE THREAD

**Issue by DeltaCopy** [arcolinux/sofirem-dev#8]
Investigate the package install/removal of both packages

**Comment by DeltaCopy** [comment]
- paru

paru-bin >> in conflict with paru
paru-git >> in conflict with paru

You can't have them all installed all at once.
So just keep one of the above packages.

**Comment by arcolinuxz** [comment]
same for yay yay-bin yay-git

**Comment by DeltaCopy** [comment]
Pending merge and testing: https://github.com/arcolinux/sofirem-dev/pull/9
